language: r
r:
  - oldrel
  - release
  - devel
cache: packages

r_packages:
  - testthat
  - rmarkdown
  - knitr
  - randomForest
  - ggplot2
  - reshape2

before_install:
  - cd pkg

notifications:
  email:
    on_success: change
    on_failure: change